### ISSUE TITLE
Wireframes

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#1]
@hannahkane @mehan @mmmavis here is a very rough initial sketch of how the content layout could work. Depending how much content we end up having, we might get everything onto one page if we use tabs.

Please add comments and feedback in Redpen: https://redpen.io/yja7196949cc09f284

### Content suggestions
**Top banner**
Short intro about the challenge with Apply Now button (links to external form)

**About Challenges**
Details specific to each challenge.

**Tabs**
FAQ, Events, and Resources will be in tabs (similar to https://science.mozilla.org/programs/fellowships/overview). 
- FAQ - accordion style expandable questions like in the example above
- Events - brief intro to the 4 events with links to google form to rsvp 
- Resources - list of links to external resources

**Forum**
Sentence with a link to external Discourse forum.

**Apply Now**
Main call to action. Links to external form. 
Different states depending on stage of the process:
- Before application opens: no button, just the date applications open
- During application: button plus date application closes
- After application: application closed text plus date for when application opens again
...

**Footer**
Usual MoFo footer https://github.com/mozilla/mofo-bootstrap/issues/92 links could include Discourse, Twitter, Contact, Legal...

![nsf-wireframe](https://cloud.githubusercontent.com/assets/1068783/21693664/9d1f13fc-d336-11e6-814e-f80f4d75b93b.jpg)

**Comment by hannahkane** [comment]
Thanks, @kristinashu. This is very helpful for getting a conversation started. I love the idea of using tabs to keep this feeling like its own world—this could work whether it's a stand-alone site, or part of another site.

A few questions, perhaps mostly for @mehan:
 * Is "Apply Now" the right terminology? Are they filling out an application or are they submitting a project? Or do they first apply to essentially get enrolled/indicate interest, and then later submit?
 * What role do the events play? Are they required for people who want to submit? Or strongly encouraged? How would you summarize the purpose of the events (from the audience's perspective)?
 * Will NSF be okay with using our standard footer?

**Comment by kristinashu** [comment]
Added a little more detail: https://redpen.io/yja7196949cc09f284 

I'm pretty sure there will be a lot more content than what is there but we'll adapt as we go.

![nsf-wireframe-02](https://cloud.githubusercontent.com/assets/1068783/21698799/ae1be934-d34d-11e6-8f90-dd106ca25ae6.png)

**Comment by mehan** [comment]
Really excited to see how much progress you've made in just a day, @kristinashu! I like the idea of a single page site and using things like drawers and tabs to collapse some of the content. If we still end up having a lot of text on the page, perhaps we can use anchor links or similar to make it a bit faster to navigate.

Here are a few answers to your questions, @hannahkane:

> Is "Apply Now" the right terminology? Are they filling out an application or are they submitting a project? Or do they first apply to essentially get enrolled/indicate interest, and then later submit?

I think "submit a project" is closer to the right terminology...they will not be required to register before submitting something, at least that's how I'm currently envisioning it (pending what's possible with Fluxx).

> What role do the events play? Are they required for people who want to submit? Or strongly encouraged? How would you summarize the purpose of the events (from the audience's perspective)?

Attendance at the events is **not** required in order to participate (we may even want to explicitly state this on the site). From the perspective of a participant, I would say the primary reasons to attend the event would be:

- To learn more about the initiative
- To meet other people in my city who are interested in the initiative
- To discuss possible project ideas
- To meet potential teammates who I might want to work on a project with

> Will NSF be okay with using our standard footer?

Good question! I think the most prudent thing for us to do would be to run the language in the footer by them along with all of the other content. If you guys can provide me with that, I will pass it along to them. I don't imagine that they will want to review our privacy policy, code of conduct etc. (nor would we want them to) but I can confirm that with them as well.

**Comment by anmechung** [comment]
Attending events are not a requirement to submit a project, but interested participants will need to apply (hopefully via Fluxx) and be selected to attend the events (assuming more than 100 people want to attend each event) with the ultimate goal of meeting potential teammates who might work on a project together for submission.  Given this, can/should events be made more prominent? Or may be some kind of persona that helps someone see the trajectory of why attending event is great opportunity? Ideally we want to see researchers, developers, and community members form a team with each other  - people they might not meet outside of the event.  Also - even though its being event will be held in a city, we're hoping for regional participation, i.e. meet other people in the region.

**Comment by hannahkane** [comment]
Thanks for the additional info, @anmechung and @mehan.

To clarify further, what process will be used to select people to attend the events? Is it something other than first come, first served?

**Comment by anmechung** [comment]
Assuming we have more than 100 people wanting to attend, we will review applicants based on skill, expertise, interest, and try to bring together a diverse group of researchers, community members, technologists etc.  Does this help?

**Comment by mehan** [comment]
+1 to everything @anmechung said; just wanted to add that while we will almost certainly use Fluxx for the actual project submission forms, the event registration may end up just being a Google Form/Eventbrite/etc. Functionally, though, all you guys should have to do is link to an external form.

**Comment by hannahkane** [comment]
It sounds like @anmechung is right that Events likely need to be more prominent, at least leading up to them. In fact, perhaps the main CTA leading up to the events is to apply to attend. Maybe it's only after the events happen that the CTA becomes "Submit Your Project." Thoughts on this?

There's a related question in the [project timeline](https://github.com/MozillaFoundation/NSF-wireless-innovation-challenge/wiki/Project-Timeline) about whether the events should be documented on the site after the fact.

**Comment by mehan** [comment]
@hannahkane I think that makes a lot of sense!

**Comment by kristinashu** [comment]
Sounds good! I've updated the wireframe: https://redpen.io/yja7196949cc09f284

CTA: "Apply Now" is now "submit a project"

Events:
  - added a note about making the main call to action "Attend an event" instead of "Submit a project" leading up to events
  - made Events the first tab (instead of FAQ) so it is more prominent and we an add an anchor link to it
  - added some rough copy about why people should attend an event

Footer: added NSF to our footer so Mozilla and NSF have equal weight

Added Awards and Timeline section to each Challenge

Added a General Info section in case we need to add more sections of copy related to both Challenge 1 and 2

**Comment by hannahkane** [comment]
Nice additions. 

Definitely feels like we're stretching the limits of a single-page website. Once we have actual content, we may want to think about @mehan's idea of adding anchor links for navigability, or looking at other UX solutions. (I don't believe we have a component for anchor links; might be a good time to create one. @kristinashu - thoughts?)

Realizing that "Attend an Event" might be a potentially confusing CTA in the header section, since it might suggest that the events *are* the challenge. Might be solvable with copy (e.g. "Get started by attending an event" - ugh...too long), or perhaps my earlier instinct was wrong. Suggest we wait until we have more content, and then perhaps do some quick usability tests.

**Comment by mehan** [comment]
@hannahkane How about "learn more at a launch event"?

**Comment by mehan** [comment]
@kristinashu Not sure if this is something better handled at the logo design stage but one thing to consider is that as far as branding is concerned, the NSF is supposed to get top billing with Mozilla being secondary. The full name for the challenge is "The NSF Wireless Innovation for a Networked Society (WINS) Initiative, Powered by Mozilla". So we'll probably want the final branding to look more like the Equal Rating Challenge branding: 

![logo](https://cloud.githubusercontent.com/assets/1390212/21732435/55f09aa4-d40e-11e6-90b9-568a97b08d70.png)

**Comment by anmechung** [comment]
@hannahkane @mehan How about "Get started at launch event"

**Comment by kristinashu** [comment]
I've added 4 new comps to redpen https://redpen.io/p/cx1e480fd9bb50a788

These show how we could divide content into multiple pages, if there is too much content for a one-page website.

**Comment by mehan** [comment]
@anmechung "Get started at a launch event" sounds good to me.

New comps look great to me, @kristinashu!

**Comment by hannahkane** [comment]
Agreed, wireframes look good. 

I think we're at a stopping point on this ticket, until we get content (see #8), so I'm adding a "blocked" label for now.

**Comment by kristinashu** [comment]
I've updated the one-page wireframe with the amount of suggested copy in the wiki https://redpen.io/yja7196949cc09f284

Seems like the one-page site might work but we still need a better sense of what the actually copy will be.

**Comment by hannahkane** [comment]
The latest wireframes look really great, @kristinashu.

I'm hoping we can stick with the one-page layout. Biggest question for me now is whether the content in the accordion will be well served by that solution. If the "Rules and regulations" are quite long, for example, the accordion may not cut it.

**Comment by kristinashu** [comment]
Updated the wireframes: https://redpen.io/p/cx1e480fd9bb50a788

- updated with the latest copy
- added a nav bar to scroll users down the page
- added a separate page for Rules & Regulations
- moved Forum and Rules & Regulations links to the footer

**Comment by kristinashu** [comment]
Few minor updates https://redpen.io/p/cx1e480fd9bb50a788

Closing this ticket and moving on to design stage https://github.com/MozillaFoundation/NSF-wireless-innovation-challenge/issues/13
