### ISSUE TITLE
UI: Accordion Feature

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#17]
- a mofo bootstrap component 
- Only one accordion can be open at a time
- When an accordion is opened, the URL should update (example: wirelesschallenge.mozilla.org/#timeline)

**Comment by kristinashu** [comment]
Minor styling tweaks could be done to staging site.
- plus icon should be smaller 18px, not 24px
- diving lines should be further apart 60px, not 54px
- font should be slightly bigger

Comp: https://redpen.io/zt134841c7aa9c7b27
<img width="1199" alt="screen shot 2017-02-06 at 9 43 09 am" src="https://cloud.githubusercontent.com/assets/1068783/22658938/bbfd2628-ec50-11e6-90d6-93037ce6809a.png">

Staging:
<img width="1210" alt="screen shot 2017-02-06 at 9 43 19 am" src="https://cloud.githubusercontent.com/assets/1068783/22658939/bc19ccb0-ec50-11e6-863a-a357efe95256.png">

**Comment by kristinashu** [comment]
Also, missing the "When an accordion is opened, the URL should update (example: wirelesschallenge.mozilla.org/#timeline)" feature.

**Comment by mmmavis** [comment]
Hey @kristinashu , if we are also [updating URL as user scrolls](https://github.com/MozillaFoundation/NSF-wireless-innovation-challenge/issues/34), what do we do if user scrolls when an accordion section is open?

Since we have so many anchored elements on this page, I wonder if we should not update URL with main section anchor as user scrolls?

**Comment by ScottDowne** [comment]
I tested by merging the two pull requests together, seems to work pretty well, actually. Nothing broken happens.

Two downsides I can see:
1. after opening and closing a accordion item, it clears the anchor instead of setting it back to details.
2. scrolling or clicking the nav, then going back to details with an accordion item open, doesn't reset the url with the open accordion item.

Pretty easy fix we can do when we merge accordion updates into master after the nav patch has landed.

I'm fine with the nav.

**Comment by hannahkane** [comment]
handled in [code repo](https://github.com/mozilla/nsf-challenge)
