### ISSUE TITLE
Page width

### ISSUE THREAD

**Issue by kristinashu** [MozillaFoundation/NSF-wireless-innovation-challenge#28]
The page width on staging is wider than in the comps. The issue with this is that the sentences become difficult to read because there are too many words per line. 

Ideally, all the content is narrower. For example, making the body text the same width as the 4 event images on staging site.
<img width="1411" alt="screen shot 2017-02-06 at 10 24 52 am" src="https://cloud.githubusercontent.com/assets/1068783/22660479/89a18dda-ec56-11e6-9e74-1be763571e0d.png">

If that is problematic to do, then we could make the body text bigger (so there are fewer words per line).

**Comment by ScottDowne** [comment]
mofo-bootstrap is adding a content width for 1140px, seemingly. It's also never added a body text size, so I feel like that's coming from mofo bootstrap too.

@mmmavis thoughts?

**Comment by mmmavis** [comment]
@kristinashu I checked the Sketch file - the width seems to be around 913px which doesn't match [any breakpoints Bootstrap uses](https://github.com/mozilla/mofo-bootstrap/blob/gh-pages/dest/css/mofo-bootstrap.css#L638-L675).  Do we want to set a custom container width for the NSF site? If so we can override the CSS so that the width is at max 913px.

**Comment by kristinashu** [comment]
Width in sketch should be 940px but we should stick to a width listed in the bootstrap link. Could we use 992px? That would be better than want we are currently using (which I think is 1200px?).

**Comment by ScottDowne** [comment]
I'm not invested enough into bootstrap to have much of an opinion, but for what it's worth I do have a pull request that makes the images smarter and kinda fit whatever space their in better.

Not sure if we'll use it or not. I kinda want to see how this conversation plays out.

**Comment by mmmavis** [comment]
If it's just for this site I'm fine with overriding it. Otherwise I'd like to loop in other front end devs on this in case we want to lift the changes to `mofo-bootstrap`. 

Another note - Bootstrap sets the container width to be [`960px` for devices that's between 992px-1200px wide](https://github.com/mozilla/mofo-bootstrap/blob/gh-pages/dest/css/mofo-bootstrap.css#L668-L671) (not 940px) and `1140px` for devices that are wider than 1200px. If we want to make the max-width smaller we should make it `960px` instead of introducing a new value.

**Comment by kristinashu** [comment]
Yes, I think that's what I meant to say. Can we use 960px for devices that are between 992px and up? So it would be 960px for devices between 992px-1200px wide and still 960px for devices wider than 1200px.

**Comment by ScottDowne** [comment]
I'm so confused.

Why don't we just set `max-width: 960px; width: 100%;` and do away with setting width based on media queries.

**Comment by alanmoo** [comment]
The easiest way to handle something like this is to use the column system built into bootstrap. Anywhere there's a `.container` class, all children of it should be `.row` and all children of that should be `.col-` classes. With this approach, you can add in breakpoints based on number of columns pretty easily. They might not be specific number widths, but they'll be consistent across the site if you stick with this approach. So in this case you could use `class="col-sm col-lg-9"` or something like that on the paragraph tag that has the text, once you put it inside a `<div class="row">`.

**Comment by kristinashu** [comment]
Noting that is also an issue on the science site https://github.com/mozilla/science.mozilla.org/issues/340

**Comment by kristinashu** [comment]
If I understand [this comment](https://github.com/mozilla/mofo-bootstrap/issues/106#issuecomment-280786845) correctly, I believe what we want to do here is "use 12 columns wide up to medium viewports, then 10 columns for large and XL." Does that make sense to everyone?

Also just to clarify, I'm talking about all the content, not only the text in the Events section.

**Comment by kristinashu** [comment]
Here's a screen cap of the sketch file:

<img width="954" alt="screen shot 2017-02-17 at 3 33 28 pm" src="https://cloud.githubusercontent.com/assets/1068783/23087123/8a69ce7a-f526-11e6-90f4-25a1c2791bf8.png">

**Comment by hannahkane** [comment]
Opened in [code repo](https://github.com/mozilla/nsf-challenge/issues/61). Closing here.
